# language: node_js
# sudo: false
# node_js:
#   - 10.15.1
# script:
#   - yarn test
#   - bash scripts/deploy-to-gh-pages.sh
language: node_js
node_js:
- lts/*
env:
# 一次构建中传多个环境变量，必须写在同一行，使用空格分开。
# - API_SERVER=xxx PUBLIC_PATH=xxx
# 默认是yarn, 如果有yarn.lock的话
install:
- yarn
# 默认是 yarn test
script:
- yarn test
- yarn build
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: build
  on:
    branch: master
  token: $TRAVIS_DEPLOY_TOKEN
  github-token: $GITHUB_TOKEN